
package service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* CommercialWSService service = new CommercialWSService();
* CommercialWSDelegate portType = service.getCommercialWSPort();
* portType.listProduit(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "CommercialWSService", targetNamespace = "http://serviceWS/", wsdlLocation = "http://localhost:8080/Gestion_Commercial/CommercialWSPort?WSDL")
public class CommercialWSService extends Service {

	private final static URL COMMERCIALWSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(service.CommercialWSService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = service.CommercialWSService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/Gestion_Commercial/CommercialWSPort?WSDL");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:8080/Gestion_Commercial/CommercialWSPort?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COMMERCIALWSSERVICE_WSDL_LOCATION = url;
	}

	public CommercialWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CommercialWSService() {
		super(COMMERCIALWSSERVICE_WSDL_LOCATION, new QName("http://serviceWS/", "CommercialWSService"));
	}

	/**
	 * 
	 * @return returns CommercialWSDelegate
	 */
	@WebEndpoint(name = "CommercialWSPort")
	public CommercialWSDelegate getCommercialWSPort() {
		return super.getPort(new QName("http://serviceWS/", "CommercialWSPort"), CommercialWSDelegate.class);
	}

}
