
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CommercialWSDelegate", targetNamespace = "http://serviceWS/")
public interface CommercialWSDelegate {

	/**
	 * 
	 * @return returns java.util.List<service.ProduitsPrix>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listProduit", targetNamespace = "http://serviceWS/", className = "service.ListProduit")
	@ResponseWrapper(localName = "listProduitResponse", targetNamespace = "http://serviceWS/", className = "service.ListProduitResponse")
	public List<ProduitsPrix> listProduit();

	/**
	 * 
	 * @param codePdt
	 * @param client
	 * @param dateCmd
	 * @param qteCmd
	 * @param codeCmd
	 * @return returns int
	 */
	@WebMethod(operationName = "AjouterCommande")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AjouterCommande", targetNamespace = "http://serviceWS/", className = "service.AjouterCommande")
	@ResponseWrapper(localName = "AjouterCommandeResponse", targetNamespace = "http://serviceWS/", className = "service.AjouterCommandeResponse")
	public int ajouterCommande(@WebParam(name = "codeCmd", targetNamespace = "") int codeCmd,
			@WebParam(name = "client", targetNamespace = "") String client,
			@WebParam(name = "codePdt", targetNamespace = "") int codePdt,
			@WebParam(name = "qteCmd", targetNamespace = "") int qteCmd,
			@WebParam(name = "dateCmd", targetNamespace = "") XMLGregorianCalendar dateCmd);

}
